### PR TITLE
bump ingress-nginx client_max_body_size

### PR DESCRIPTION
**Pull request by cg505**
This will allow for larger media uplods.

### CODE REVIEW

**Comment by cg505** [comment]
Build failed due to tootsuite/mastodon#13292.

**Comment by cg505** [comment]
Gonna rebase once #11 is merged to get a good build.

**Review by ja5087 — APPROVED** [review]
While I think 16m is big enough for images, it's interesting how they chose 80m as the default in https://github.com/tootsuite/mastodon/blob/6c79b7237e31eb510af7df3f4f2cb133dea39845/dist/nginx.conf#L41

**Comment by cg505** [comment]
good catch, we may as well make these line up

**Review by ja5087 — APPROVED** [review]

**Comment by cg505** [comment]
@ja5087 sorry for so many re-requested reviews

**Review by ja5087 — APPROVED** [review]
no worries, sucks that we need the patches otherwise we could just download the release directly and avoid `rm`-gating

**Pull request merged**
